# Generated by Django 2.2.7 on 2019-11-13 20:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=1024, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='mob_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='account',
            name='referral_source',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Referral Source'),
        ),
        migrations.AddField(
            model_name='account',
            name='story',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Personal Story'),
        ),
        migrations.AddField(
            model_name='account',
            name='tel_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Telephone Number'),
        ),
        migrations.AddField(
            model_name='account',
            name='website_url',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='account',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
