# Generated by Django 2.2.7 on 2019-11-17 00:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191113_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address1',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address2',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mob_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tel_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
