# Generated by Django 2.1.1 on 2019-11-17 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191117_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='store_description',
            field=models.CharField(max_length=1024, null=True, verbose_name='Store name'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='store_name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL),
        ),
    ]
