# Generated by Django 2.2.7 on 2019-11-17 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
