# Generated by Django 2.1.1 on 2019-11-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191117_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='store_description',
            field=models.CharField(max_length=1024, null=True, verbose_name='Store description'),
        ),
    ]
