# Generated by Django 2.2.7 on 2019-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0005_auto_20191117_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='shop.Category'),
        ),
    ]
