# Generated by Django 2.1.11 on 2019-11-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191117_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
