# Generated by Django 2.1.11 on 2019-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191120_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='primary',
            field=models.BooleanField(null=True),
        ),
    ]
