# Generated by Django 2.1.11 on 2019-11-22 23:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191119_1900'),
        ('shop', '0005_category_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category', models.ManyToManyField(related_name='products', to='shop.Category')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.Merchant')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
