# Generated by Django 2.1.11 on 2019-11-22 23:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
